# Generated by Django 3.0.7 on 2020-06-06 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_auto_20200606_0451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='data_pedido',
        ),
    ]
