# Generated by Django 3.0.7 on 2020-06-06 02:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='autor',
        ),
        migrations.AlterField(
            model_name='aula',
            name='publicado',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 2, 28, 2, 613688, tzinfo=utc)),
        ),
    ]
