# Generated by Django 3.0.7 on 2020-06-06 03:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200605_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='publicado',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 3, 16, 6, 353381, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameAutor', models.CharField(max_length=100)),
                ('coment', models.TextField()),
                ('ativado', models.BooleanField(default=True)),
                ('publicado', models.DateTimeField(default=datetime.datetime(2020, 6, 6, 3, 16, 6, 354378, tzinfo=utc))),
                ('aulaCodigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Aula')),
            ],
        ),
    ]
