# Generated by Django 3.0.7 on 2020-06-06 03:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200606_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='sexo',
            field=models.CharField(choices=[('M', 'Maculino'), ('F', 'Feminino')], default='M', max_length=10),
        ),
        migrations.AlterField(
            model_name='aula',
            name='publicado',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 3, 26, 51, 188100, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='publicado',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 3, 26, 51, 188100, tzinfo=utc)),
        ),
    ]
