# Generated by Django 3.0.7 on 2020-06-06 07:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20200606_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='publicado',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 7, 58, 3, 893252, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='publicado',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 7, 58, 3, 893252, tzinfo=utc)),
        ),
    ]
