# Generated by Django 3.0 on 2020-06-13 15:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20200613_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='image',
            field=models.ImageField(blank=True, max_length=180, null=True, upload_to=website.models.upload_path),
        ),
        migrations.AlterField(
            model_name='aula',
            name='publicado',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 13, 15, 57, 34, 590542, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='publicado',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 13, 15, 57, 34, 591593, tzinfo=utc)),
        ),
    ]
